In [85]:
import pandas as pd

In [86]:
df = pd.read_csv('data/examples.csv')

In [87]:
df

description  label
0   Poszukujemy osoby do obsługi klienta, która bę...      1
1   \n\nPoszukujemy Specjalisty ds. Obsługi Klient...      1
2   \nStanowisko: Specjalista ds. Obsługi Klienta ...      1
3   \n\nStanowisko: Specjalista ds. Obsługi Klient...      1
4   \n\nStanowisko: Specjalista ds. Obsługi Klient...      1
5   \n\nBet365 - recenzja renomowanego bukmachera ...      1
6   \n\nBet365 - charakterystyka renomowanego bukm...      1
7   \n\nOpisując bukmachera Bet365, nie sposób nie...      1
8   \n\nBet365, lider wśród bukmacherów, wyróżnia ...      1
9   \n\nBet365 to niekwestionowany lider wśród buk...      1
10  \n\n1. Przedmiotem sprzedaży jest Konto Bankow...      1
11  \n\n1. Przedmiotem sprzedaży jest Konto Bankow...      1
12  \n\n1. Przedmiotem oferty jest Konto Bankowe d...      1
13  \n\n1. Przedmiotem sprzedaży jest Konto Bankow...      1
14  \nPoszukujemy osoby, która specjalizuje się w ...      1
15  \n „Konto bankowe, anonimowe, pewne na 100%! W...      1
16  \nMamy dostępne konto bankowe, które zapewnia ...      1
17  \nSprzedam konta bankowe bez obciążeń. Dostępn...      1
18  \nOferuję do sprzedaży konta bankowe bez żadny...      1
19  \nPosiadam na sprzedaż konta bankowe, które są...      1
20  \nMam na sprzedaż konta bankowe, które są woln...      1
21  \nMasz problem z komornikiem? Co miesiąc zamra...      1
22  \nOferujemy rozwiązanie dla osób mających prob...      1
23  \nMamy rozwiązanie dla osób borykających się z...      1
24  \nWitam, Sprzedajemy Konta Bankowe Na Słupa Be...      1
25                                                NaN      0
26  \nSAMODZIELNA KSIĘGOWA\n\nTwój zakres obowiązk...      0
27  \nManpower (Agencja zatrudnienia nr 412) to gl...      0
28  \nZatrudnimy doracę, doradczynię ds. kontaktu ...      0
29  \nManpower (Agencja zatrudnienia nr 412) to gl...      0
30  \nManpower (Agencja zatrudnienia nr 412) to gl...      0
31  \nManpower (Agencja zatrudnienia nr 412) to gl...      0
32  \nSzukam ambitnych osób do zespołu, które nie ...      0
33  \nLUBISZ DORADZAĆ INNYM? RÓB TO Z NAMI!\nDorad...      0
34  \nDoradca Klienta / Doradca finansowy\nOpis st...      0
35  \nJeżeli chcesz pracować w stabilnej firmie, d...      0
36  \nZatrudnię na stanowisku doradcy klienta w bi...      0
37  \nNa co dzień jako nasz Doradca:\nmasz bezpośr...      0
38  \nW związku z rozwojem lubelskiego oddziału po...      0
39  \nSprzedam fulla marki\nTrek Topfuel 9.8 SL ca...      0
40  \nNa sprzedaż używane w gravelu koła 28'' 622x...      0
41  \nSiodełko klasyczne czarna panterka\n30 zł\nP...      0
42  \nNOWY 2023r+Gratisy|Rower Górski CARAIMAN EXP...      0
43  \nPrywatne\nStan: Używane\nOPIS\nKoła– 12 cali...      0
44  \nTelefon Huawei P40 PRO 8GB / 256GB\n1 199 zł...      0
45  \nPrzystawka stół do rzepaku class 3m\n6 500 z...      0
46  \nKosiarka dyskowa przeznaczona jest do koszen...      0

In [88]:
df = df.dropna()

In [102]:
import spacy

nlp = spacy.load("pl_core_news_md")

In [103]:
text = "kupię konto"

processed = nlp(text)

In [105]:
[word.lemma_ for word in processed]

['kupić', 'konto']

In [90]:
df['vector'] = df['description'].apply(lambda d: nlp(d).vector)

/tmp/ipykernel_13751/916003499.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['vector'] = df['description'].apply(lambda d: nlp(d).vector)


In [91]:
df

description  label   
0   Poszukujemy osoby do obsługi klienta, która bę...      1  \
1   \n\nPoszukujemy Specjalisty ds. Obsługi Klient...      1   
2   \nStanowisko: Specjalista ds. Obsługi Klienta ...      1   
3   \n\nStanowisko: Specjalista ds. Obsługi Klient...      1   
4   \n\nStanowisko: Specjalista ds. Obsługi Klient...      1   
5   \n\nBet365 - recenzja renomowanego bukmachera ...      1   
6   \n\nBet365 - charakterystyka renomowanego bukm...      1   
7   \n\nOpisując bukmachera Bet365, nie sposób nie...      1   
8   \n\nBet365, lider wśród bukmacherów, wyróżnia ...      1   
9   \n\nBet365 to niekwestionowany lider wśród buk...      1   
10  \n\n1. Przedmiotem sprzedaży jest Konto Bankow...      1   
11  \n\n1. Przedmiotem sprzedaży jest Konto Bankow...      1   
12  \n\n1. Przedmiotem oferty jest Konto Bankowe d...      1   
13  \n\n1. Przedmiotem sprzedaży jest Konto Bankow...      1   
14  \nPoszukujemy osoby, która specjalizuje się w ...      1   
15  \n „Konto bankowe, anonimowe, pewne na 100%! W...      1   
16  \nMamy dostępne konto bankowe, które zapewnia ...      1   
17  \nSprzedam konta bankowe bez obciążeń. Dostępn...      1   
18  \nOferuję do sprzedaży konta bankowe bez żadny...      1   
19  \nPosiadam na sprzedaż konta bankowe, które są...      1   
20  \nMam na sprzedaż konta bankowe, które są woln...      1   
21  \nMasz problem z komornikiem? Co miesiąc zamra...      1   
22  \nOferujemy rozwiązanie dla osób mających prob...      1   
23  \nMamy rozwiązanie dla osób borykających się z...      1   
24  \nWitam, Sprzedajemy Konta Bankowe Na Słupa Be...      1   
26  \nSAMODZIELNA KSIĘGOWA\n\nTwój zakres obowiązk...      0   
27  \nManpower (Agencja zatrudnienia nr 412) to gl...      0   
28  \nZatrudnimy doracę, doradczynię ds. kontaktu ...      0   
29  \nManpower (Agencja zatrudnienia nr 412) to gl...      0   
30  \nManpower (Agencja zatrudnienia nr 412) to gl...      0   
31  \nManpower (Agencja zatrudnienia nr 412) to gl...      0   
32  \nSzukam ambitnych osób do zespołu, które nie ...      0   
33  \nLUBISZ DORADZAĆ INNYM? RÓB TO Z NAMI!\nDorad...      0   
34  \nDoradca Klienta / Doradca finansowy\nOpis st...      0   
35  \nJeżeli chcesz pracować w stabilnej firmie, d...      0   
36  \nZatrudnię na stanowisku doradcy klienta w bi...      0   
37  \nNa co dzień jako nasz Doradca:\nmasz bezpośr...      0   
38  \nW związku z rozwojem lubelskiego oddziału po...      0   
39  \nSprzedam fulla marki\nTrek Topfuel 9.8 SL ca...      0   
40  \nNa sprzedaż używane w gravelu koła 28'' 622x...      0   
41  \nSiodełko klasyczne czarna panterka\n30 zł\nP...      0   
42  \nNOWY 2023r+Gratisy|Rower Górski CARAIMAN EXP...      0   
43  \nPrywatne\nStan: Używane\nOPIS\nKoła– 12 cali...      0   
44  \nTelefon Huawei P40 PRO 8GB / 256GB\n1 199 zł...      0   
45  \nPrzystawka stół do rzepaku class 3m\n6 500 z...      0   
46  \nKosiarka dyskowa przeznaczona jest do koszen...      0   

                                               vector  
0   [-0.16633095, -0.57764673, -0.2857735, 0.03326...  
1   [0.051669978, -0.58677876, -0.303576, -0.12005...  
2   [0.09012246, -0.30561966, -0.037855927, -0.148...  
3   [0.12185417, -0.32749996, -0.13016821, -0.2932...  
4   [0.29417562, -0.50558317, -0.10031808, -0.0974...  
5   [-0.025440084, -0.9623769, -0.7061211, -0.0519...  
6   [0.112140626, -0.8139154, -0.65025824, -0.1102...  
7   [0.1724798, -0.81884354, -0.7808593, -0.158611...  
8   [0.124690175, -0.6240491, -0.5909958, -0.33469...  
9   [0.10929345, -0.61537695, -0.4594767, -0.31324...  
10  [0.15366189, -0.98701656, -0.3368005, -0.18235...  
11  [0.17786631, -1.1746465, -0.3590199, -0.144238...  
12  [0.16258185, -1.0300758, -0.52306384, -0.19594...  
13  [0.20901844, -1.0015261, -0.494371, -0.2005076...  
14  [0.06644402, -0.60004276, -0.3748896, -0.18304...  
15  [0.68412834, -1.025501, -0.861978, -0.10058319...  
16  [0.7202196, -1.2260975, -0.8819563, -0.5173696...  
17  [-0.46089828, -1.0734

In [92]:
data = df['vector'].to_numpy()

In [93]:
data = np.stack(data)

In [94]:
data

array([[-0.16633095, -0.57764673, -0.2857735 , ...,  0.9075666 ,
        -0.87476283,  0.1515256 ],
       [ 0.05166998, -0.58677876, -0.303576  , ...,  0.7895068 ,
        -0.77655613,  0.17532067],
       [ 0.09012246, -0.30561966, -0.03785593, ...,  0.68255585,
        -0.9080231 ,  0.15442146],
       ...,
       [-0.14504547, -0.81079525, -0.14779225, ...,  0.48733088,
        -0.2888635 ,  0.14878169],
       [ 0.39854   ,  0.17775695, -0.250905  , ...,  0.05196178,
         0.67713964,  0.33840212],
       [ 0.32132372, -0.91506827, -0.85574037, ...,  0.78654057,
        -0.19381583,  0.53613347]], dtype=float32)

In [95]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline

In [96]:
scaler = MinMaxScaler()
model = MultinomialNB()
pipeline = make_pipeline(scaler, model)

In [97]:
pipeline.fit(data, df['label'])

Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                ('multinomialnb', MultinomialNB())])

In [98]:
import numpy as np

In [99]:
np.array([[2,2],[2,2]])

array([[2, 2],
       [2, 2]])

In [100]:
pipeline.predict(data[-1].reshape(1,-1))

array([0])

In [101]:
df.tail()

description  label   
42  \nNOWY 2023r+Gratisy|Rower Górski CARAIMAN EXP...      0  \
43  \nPrywatne\nStan: Używane\nOPIS\nKoła– 12 cali...      0   
44  \nTelefon Huawei P40 PRO 8GB / 256GB\n1 199 zł...      0   
45  \nPrzystawka stół do rzepaku class 3m\n6 500 z...      0   
46  \nKosiarka dyskowa przeznaczona jest do koszen...      0   

                                               vector  
42  [0.34073585, -0.21261212, -0.3672222, 0.214677...  
43  [0.9285452, -0.64686936, -0.64517665, 0.119448...  
44  [-0.14504547, -0.81079525, -0.14779225, -0.168...  
45  [0.39854, 0.17775695, -0.250905, 0.30155268, -...  
46  [0.32132372, -0.91506827, -0.85574037, 0.47872...

In [ ]:
from sklearn.metrics import 